config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'
  get '/search' => 'search#search'
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200 }
  
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :relationships, class_name:"Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :reverce_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverce_of_relationships, source: :follower
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end
  
  attachment :profile_image

  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  

  def after_sign_in_path_for(resource)
    user_path(resource)
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
  end

  def destroy
  	@book = Book.find(params[:book_id])
  	@book_comment = BookComment.new
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:content)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    if @book_new.save
      flash[:notice] = 'You have created book successfully.'
      redirect_to book_path(@book_new.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book_new = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = current_user
    @book_new = Book.new
    @user_new = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end  
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = 'You have updated book successfully.'
      redirect_to book_path(@book.id)
    else
      render :edit
    end  
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end  
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @model = params["search"]["model"]
    @value = params["search"]["value"]
    @how = params["search"]["how"]
    @datas = search_for(@how, @model, @value)
  end
  private

  def match(model, value)
    if model == 'user'
      User.where(name: value)
    elsif model == 'book'
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how, model, value)
    case how
    when 'match'
      match(model, value)
    when 'forward'
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_post,only: [:edit]
  
  def index
    @users = User.all
    @user = current_user
    @book_new = Book.new
  end

  def show
    @user = User.find(params[:id])
    @book_new = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'You have updated user successfully.'
      redirect_to user_path(@user.id)
    else
      render :edit
    end  
  end
  
  def correct_post
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user)
    end
  end

  private
  def user_params
    params.require(:user).permit(:profile_image, :name, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.js.erb
$(".comment").html("<%= j(render 'books/comment', book: @book,book_comment: @book_comment) %>");
$(".comment_form").val('');

app/views/book_comments/destroy.js.erb
$(".comment").html("<%= j(render 'books/comment', book: @book,book_comment: @book_comment) %>");

app/views/books/_comment.html.erb
<table>
  <% @book.book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= link_to user_path(@book.user) do %>
        <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %><br>
        <%= @book.user.name %>
        <% end %>
      </td>
      <td>
        <%= book_comment.content %>
      </td>
      <% if book_comment.user == current_user %>
      <td>
        <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class:'btn btn-sm btn-danger' %>
      </td>
      <% end %>
    </tr>
  <% end %>
</table>
  <%= form_with(model:[@book, @book_comment], remote: true) do |f| %>
    <%= f.text_area :content, size:"90*5", class:'comment_form' %><br>
    <%= f.submit "送信" %>
  <% end %>

app/views/books/_list.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr></tr>
      <tr>
        <th>name</th>
        <th><%= @user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th>
          <%= link_to user_followers_path(@user) do %>
            <%= @user.followings.count %>
          <% end %>
        </th>
      </tr>
      <tr>
        <th>folowers</th>
        <th>
          <%= link_to user_followers_path(@user) do %>
            <%= @user.followers.count %>
          <% end %>
        </th>
      </tr>
    </tbody>
  </table>

  <div class="row">
    <%= link_to '', edit_user_path(@user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
  </div>
  <h2 class="mt-3">New book</h2>
  <%= form_with model:book, url:'/books', local:true do |f| %>
    <h4>Tittle</h4>
    <%= f.text_field :title %>
    <h4>Opinion</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Create Book', class:"btn btn-success" %>
  <% end %>
</div>

app/views/books/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>Editing Book</h2>
          <% if @book.errors.any? %>
            <p style="color: red;"><%= @book.errors.count %>errors prohibited this obj from being saved:</br>
            <% @book.errors.full_messages.each do |message| %>
              <%= message %>
              </br>
            <% end %>
          <% end %>
          <%=form_with model:@book, local:true do |f| %>
              <label for="book_title">Title</label></br>
              <%= f.text_field :title %></br>

              <label for="book_opinion">Opinion</label></br>
              <%= f.text_field :body %></br>
              <%= f.submit 'Update Book', class: 'btn btn-success' %>
          <% end %>
          <%= link_to 'Show', book_path(@book.id) %>
          |
          <%= link_to 'Back', books_path %>
      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<head>
  <title>Bookers2</title>
  <script src="https://kit.fontawesome.com/a334d13857.js" crossorigin="anonymous"></script>
</head>

<main>
  <div class="container px-5 px-sm-0">
    <% if @book_new.errors.any? %>
      <p style="color: red;"><%= @book_new.errors.count %>errors prohibited this obj from being saved:</br>
      <% @book_new.errors.full_messages.each do |message| %>
        <%= message %>
        </br>
      <% end %>
    <% end %>
    <div class="row">
      <%= render 'books/list', book: @book_new %>
      <div class="col-md-8 offset-md-1">
        <h2>Book</h2>
        <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
          <tbody>
            <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book.id) %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td id= "favorite_btn<%= book.id %>">
                <%= render 'favorites/favorites_btn', book: book %>
              </td>
              <td>
                <p>コメント数: <%= book.book_comments.count %></p>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/new.html.erb
<h2>User info</h2>

<h2>New book</h2>
<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_field :body %>
  <%= f.submit '投稿' %>
<% end %>

app/views/books/show.html.erb
<head>
  <title>Bookers2</title>
  <script src="https://kit.fontawesome.com/a334d13857.js" crossorigin="anonymous"></script>
</head>

<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user_new, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= @user_new.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user_new.introduction %></th>
            </tr>
          </tbody>
        </table>
        <div class="row">
          <%= link_to '', edit_user_path(@user_new), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>
        <h2 class="mt-3">New book</h2>
        <%= form_with model:@book_new, local:true do |f| %>
          <h4>Tittle</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
          <tbody>
            <tr>
              <td>
                <%= link_to user_path(@book.user) do %>
                <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %></br>
                <%= @book.user.name %>
                <% end %>
              </td>
              <td>
                <%= link_to @book.title, book_path(@book.id) %>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <td>
                <% if @book.user == current_user %>
                <%= link_to 'Edit', edit_book_path(@book), class:'btn btn-sm btn-success' %>
                <% end %>
              </td>
              <td>
                <% if @book.user == current_user %>
                <%= link_to "Destroy", book_path(@book), method: :delete, class:'btn btn-sm btn-danger' %>
                <% end %>
              </td>
              <td id= "favorite_btn<%= @book.id %>">
                <%= render 'favorites/favorites_btn', book: @book %>
              </td>
              <td>
                <%= link_to "#{@book.book_comments.count} コメント", book_path(@book.id) %></p>
              </td>
            </tr>
          </tbody>
        </table>
        <div class= "comment">
          <%= render 'books/comment', book: @book,book_comment: @book_comment %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/favorites/_favorites_btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :delete, remote: true, class: "fas fa-heart heart_red" %>
<% else %>
  <%= link_to book.favorites.count, book_favorites_path(book), method: :post, remote: true, class: "fas fa-heart heart_blue" %>
<% end %>

app/views/favorites/create.js.erb
$('#favorite_btn<%= @book.id %>').html("<%= j(render partial: 'favorites/favorites_btn', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$('#favorite_btn<%= @book.id %>').html("<%= j(render partial: 'favorites/favorites_btn', locals: {book: @book}) %>");

app/views/homes/about.html.erb
<main>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        
      </h1>
    </div>
  </div>
</main>

app/views/homes/show.html.erb
<main>
  <div class="container">
    <div class="row">
      <h1 class="px-3 mx-auto">
        Welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        
      </h1>
    </div>
  </div>
</main>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>
        welcome to
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        !!
      </h1>

      <p>In
        <i class="fas fa-book"></i>
        <strong>Bookers</strong>
        ,
      </p>

      <p>
        you can share and exchange your opinions, inpressions, and emotions</br>
        about various books!
      </p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" <%= link_to "Log in", new_user_session_path %></a class>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" <%= link_to "Sign up", new_user_registration_path %></a class>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/_follow_button.html.erb
<% if current_user.following?(user) %>
  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
<% else %>
  <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
<% end %>

app/views/relationships/followers.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-sm-12">
      <h2>Follower Users</h2>
        <table class="table">
        <% if @users.exists? %>
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %></td>
                <td><%= user.name %></td>
                <td>フォロー数: <%= user.followings.count %></td>
                <td>フォロワー数: <%= user.followers.count %></td>
                <td><%= link_to 'Show', user_path(user.id) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <% else %>
          <p>ユーザーはいません</p>
        <% end %>
    </div>
  </div>
</div>

app/views/search/_search_box.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-8 offset-md-4" style="margin-top: 25px;">
      <% if user_signed_in? %>
        <%= form_with url:search_path, method: :get, local: true do |f| %>
          <%= f.text_field 'search[value]' %>
          <%= f.select 'search[model]', options_for_select({ "User" => "user", "Book" => "book" }) %>
          <%= f.select 'search[how]', options_for_select({ "完全一致" => "match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"  }) %>
          <%= f.submit :"検索" %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/search/search.html.erb
<div class="container">
  <div class="col-xs-12">
    <% if @model == "user" %>
    <h2>Users search for '<%= @value %>'</h2>
    <table class="table">
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Introduction</th>
            </tr>
        </thead>
    <% @datas.each do |user| %>
        <tbody>
            <tr>
                <th>
                  <%= attachment_image_tag(user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
                </th>
                <th>
                  <%= user.name %>
                </th>
                <th>
                  <%= user.introduction %>
                </th>
            </tr>
        </tbody>
    <% end %>
    <% elsif @model == "book" %>
    <h2>Books search for '<%= @value %>'</h2>
    <table class="table">
        <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
            </tr>
        </thead>
        <% @datas.each do |book| %>
        <tbody>
            <tr>
                <th>
                  <%= attachment_image_tag(book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40') %>
                </th>
                <th>
                  <%= book.title %>
                </th>
                <th>
                  <%= book.body %>
                </th>
            </tr>
        </tbody>
        <% end %>
    <% end %>
    </table>
  </div>
</div>

app/views/users/edit.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
        <% if @user.errors.any? %>
          <p style="color: red;"><%= @user.errors.count %>errors prohibited this obj from being saved:</br>
          <% @user.errors.full_messages.each do |message| %>
            <%= message %>
            </br>
          <% end %>
        <% end %>
          <%=form_with model:@user, local:true do |f| %>
              <label for="user_name">Name</label></br>
              <%= f.text_field :name %></br>
              <label for="user_image">Image</label></br>
              <%= f.attachment_field :profile_image %></br>
              <label for="user_introduction">Introduction</label></br>
              <%= f.text_field :introduction %></br>
              <%= f.submit 'Update User', class: 'btn btn-secondary' %>
          <% end %>
      </div>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<head>
  <title>Bookers2</title>
  <script src="https://kit.fontawesome.com/a334d13857.js" crossorigin="anonymous"></script>
</head>

<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <%= render 'books/list', book: @book_new %>

      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table class="table">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
                <th colspan="3"></th>
              </tr>
            </thead>
          <tbody>
            <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                フォロー数：<%= user.followings.count %>
              </td>
              <td>
                フォロワー数<%= user.followers.count %>
              </td>
              <td>
                <%= render 'relationships/follow_button', user: user %>
              </td>
              <td>
                <%= link_to 'Show', user_path(user.id) %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<head>
  <title>Bookers2</title>
  <script src="https://kit.fontawesome.com/a334d13857.js" crossorigin="anonymous"></script>
</head>

<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
        <table class="table">
          <tbody>
            <tr></tr>
            <tr>
              <th>name</th>
              <th><%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction</th>
              <th><%= @user.introduction %></th>
            </tr>
            <tr>
              <th>follows</th>
              <th>
                <%= link_to user_followers_path(@user) do %>
                  <%= @user.followings.count %>
                <% end %>
              </th>
            </tr>
            <tr>
              <th>folowers</th>
              <th>
                <%= link_to user_followers_path(@user) do %>
                  <%= @user.followers.count %>
                <% end %>
              </th>
            </tr>
            <tr>
              <th>
                <% if current_user.id != @user.id %>
                  <% if current_user.following?(@user) %>
                    <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class:"btn btn-info" %>
                  <% else %>
                    <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class:"btn btn-success" %>
                  <% end %>
                <% end %>
              </th>
            </tr>
          </tbody>
        </table>

        <div class="row">
          <%= link_to '', edit_user_path(@user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" %>
        </div>

        <h2 class="mt-3">New book</h2>
        <%= form_with model:@book, url:'/books', local:true do |f| %>
          <h4>Tittle</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>
            </thead>
          <tbody>
            <% @user.books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(@user) do %>
                <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', size: "40x40", fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book.id) %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td>
                <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></p>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>